baseURL = "https://robamu.github.io"
languageCode = 'en-us'
title = 'Robins blog'
theme = "PaperMod"
disqusShortname = "https-robamu-github-io"

pygmentsStyle = "pygments"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
  title = "robins blog"
  keyword = "coding, rust, c++, python, aerospace, satellites"
  commit = false
  comments = true
  goatcounter = "robamu"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowWordCount = false
  ShowPageViews = true
  ShowCodeCopyButtons = true
  socialShare = true
  showRelatedPosts = true
  # Google Programmable Search Engine
  gcse = "49f27010d1fda4554"
  # Footer section
  [params.footer]
    enable = true

[Author]
name = "Robin Mueller"
github = "robamu"
linkedin = "robin-mueller-m"

[menu]

[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "About"
url = "about"
weight = 2

[[menu.main]]
name = "Contact"
url = "contact"
weight = 3
